services:

  users-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  orders-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  graphql-bff:
    build: ./api-gateway-graphql
    container_name: api-gateway-graphql
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - USERS_API_URL=http://users-service:8080
      - ORDERS_API_URL=http://orders-service:8081
    depends_on:
      - users-service
      - orders-service
