spring:
  application:
    name: api-gateway-graphql
  graphql:
    introspection:
      enabled: true
server:
  port: 9090
user:
  service:
    base-url: ${USERS_API_URL:http://localhost:8080}
order:
  service:
    base-url: ${ORDERS_API_URL:http://localhost:8081}




